name: k6

on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn
      - run: yarn build

      - uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v2.12.2

      # https://k6.io/docs/results-output/real-time/datadog/
      - uses: DataDog/agent-github-action@v1.3.1
        with:
          api_key: ${{ secrets.DATADOG_API_KEY }}
      - run: k6 run lib/http-get.js
        env:
          K6_OUT: statsd
          K6_STATSD_ENABLE_TAGS: true
